config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'todo_lists#index'
  resources :users, only: [:edit, :update]
  resources :todo_lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true
  validates :lank, :star, :deadline_date, presence: true

  enum lanks: [:'D', :'C', :'B', :'A', :'S']
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todo_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  # uniqueness: true, length: { maximum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def production?
    Rails.env.production?
  end

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  #   end
  # end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

  def index
    @todoLists = TodoList.order("created_at DESC").where(user_id: "#{current_user.id}")
  end

  def new
    @todoLists = TodoList.new
  end

  def create
    TodoList.create(post_params)
    redirect_to root_path
  end

  def show
    @todoLists = Todolist.find_by(id: params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    todoList = TodoList.find(params[:id])
    todoList.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:todo_list).permit(:title, :content, :lank, :star, :deadline_date).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:html_title) ? yield(:html_title) : "To-Do.Projects" 
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield
  %foot
    = render 'layouts/notifications'

app/views/shared/_header_main.html.haml
.title
  = link_to 'To-Do', root_path
.user
  .user__name
    = current_user.name
    .user__name__edit
      = link_to edit_user_path(current_user) do
        = icon('fas','user-edit')
  .achievement
    .achievement__percent
    .achievement__bar
      %p#header-clock
        ※NowLoading…

app/views/shared/_main_list.html.haml
.main-list
  - @todoLists.each do |todo_list|
    .task
      .task__title
        = todo_list.title
      .task__creater
        作成者：
        = todo_list.user.name
      .task__created_at
        作成日：
        = l(todo_list.created_at, format: :long)
      .task__option
        %p.task__option__lank
          = "#{todo_list.lank}ランク"
        %p.task__option__star
          = "★×#{todo_list.star}"
        %p.task__option__d-line
          = "#{todo_list.deadline_date}まで"
        %p.task_option__limited
      .task__content
        = todo_list.content

app/views/shared/_task_bar.html.haml
.side-bar
  .task-list
    = link_to "新規作成", new_todo_list_path, class: "edit-task"
    .sort
      %p.sort__importance
        重要度
        %ul.importance-lank
          %li#lank-s
            Sランク
          %li#lank-A
            Aランク
          %li#lank-B
            Bランク
          %li#lank-C
            Cランク
          %li#lank-D
            Dランク
      %p.sort__star
        難易度別
        %ul.ster-characters
          %li#sters-5
            ★★★★★
          %li#sters-4
            ★★★★
          %li#sters-3
            ★★★
          %li#sters-2
            ★★
          %li#sters-1
            ★
      %p.sort__d-line
        期限別
        %ul.d-line-limit
          %li#limit-year
            残り1年以内
          %li#limit-month
            残り1ヶ月以内
          %li#limit-week
            残り1週間以内
          %li#limit-day
            残り3日以内
          %li#limit-over
            期限切れ

app/views/todo_lists/index.html.haml
.header
  = render "shared/header_main"
.wrapper
  = render "shared/task_bar"
  = render "shared/main_list"

app/views/todo_lists/new.html.haml
- content_for(:html_title) {'新規作成/To-Do'}

.header
  = render "shared/header_main"
.new-task
  .new-task__title
    新規作成
  .contents
    = form_for @todoLists, class: :contents__form do |f|
      = f.text_field :title, placeholder: :タイトル, class: :contents__form__title
      = f.text_area :content, placeholder: :詳細, class: :contents__form__details
      .option
        オプション
        .option__lank
          重要度
          = f.select :lank, TodoList.lanks_i18n.invert, {prompt: '選択してください'}, class: :option__lank__select
        .option__stars
          難易度
          = f.radio_button :star, "1",id: :star__1, class: :option__stars__radio
          = f.label "★", for: "star__1", class: :option__stars__label
          = f.radio_button :star, "2",id: :star__2, class: :option__stars__radio
          = f.label "★★", for: "star__2", class: :option__stars__label
          = f.radio_button :star, "3",id: :star__3, class: :option__stars__radio
          = f.label "★★★", for: "star__3", class: :option__stars__label
          = f.radio_button :star, "4",id: :star__4, class: :option__stars__radio
          = f.label "★★★★", for: "star__4", class: :option__stars__label
          = f.radio_button :star, "5",id: :star__5, class: :option__stars__radio
          = f.label "★★★★★", for: "star__5", class: :option__stars__label
        .option__d-line
          期限
          = f.date_field :deadline_date, class: "option__d-line__date"
      = f.submit "投稿", class: :submit__btn

app/views/users/edit.html.haml
- content_for(:html_title) {'ユーザー情報編集/To-Do'}

.account-page
  .header
    = render "shared/header_main"
  .account-page__content
    .contents
      %h2.contents__head
        ユーザー情報の編集
      = form_for(current_user) do |f|
        .field
          .field__label
            = f.label :name, "ニックネーム"
          .field__input
            = f.text_field :name, autofocus: true
        .field
          .field__label
            = f.label :email, "メールアドレス"
          .field__input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'action'
        .edit__login-out
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'edit__login-out__btn'
      